/**
 * Vendor-agnostic AI-generation detection normalization.
 *
 * Only maps fields that are explicitly AI-related.
 * Never derives values from model confidence, trust score, risk score, or verdict.
 */

import type { AiDetection, AiDetectionLabel } from "../types/verification";

export const UNSUPPORTED_AI_DETECTION: AiDetection = {
  supported: false,
  probability: null,
  label: "Unknown",
  explanation: null,
};

/** Keys that must never be treated as AI probability. */
const EXCLUDED_SCORE_KEYS = new Set([
  "confidence",
  "modelconfidence",
  "model_confidence",
  "trustscore",
  "trust_score",
  "documenttrustscore",
  "document_trust_score",
  "riskscore",
  "risk_score",
  "fraudscore",
  "fraud_score",
  "fraudscore100",
  "score",
  "score100",
  "score_100",
  "rawscore",
  "raw_score",
  "ocrscore",
  "ocr_score",
  "mlscore",
  "ml_score",
  "fieldfitscore",
  "field_fit_score",
]);

const EXPLICIT_PROBABILITY_KEYS = new Set([
  "aiprobability",
  "aiprob",
  "aigenerationprobability",
  "aigeneratedprobability",
  "aigeneratedscore",
  "aigenerationscore",
  "ailikelihood",
  "aisyntheticprobability",
  "syntheticprobability",
  "deepfakeprobability",
  "generatedcontentconfidence",
  "aidetectionscore",
  "aidetectionprobability",
  "generativeaiprobability",
  "generativeprobability",
  "genaiprobability",
  "aigenerationlikelihood",
  "aigeneratedconfidence",
  "aidetectionsconfidence",
  // TruthScan / AI Image Detection API — vendor "Core AI score" (`/query.result`).
  "coreaaiscore",
]);

const EXPLICIT_BOOLEAN_KEYS = new Set([
  "aigenerated",
  "isaigenerated",
  "isai",
  "is_ai",
  "generatedbyai",
  "issynthetic",
  "isdeepfake",
  "synthetic",
  "deepfake",
  "aidetection",
  "containsaigeneratedcontent",
  "hasaigeneratedcontent",
]);

function normalizeKey(key: string): string {
  return key.toLowerCase().replace(/[^a-z0-9]/g, "");
}

function asRecord(value: unknown): Record<string, unknown> {
  if (value && typeof value === "object" && !Array.isArray(value)) {
    return value as Record<string, unknown>;
  }
  return {};
}

function toScore100(raw: number | null | undefined): number | null {
  if (raw == null || !Number.isFinite(raw) || raw < 0) return null;
  if (raw <= 1) return Math.round(Math.min(100, Math.max(0, raw * 100)) * 10) / 10;
  return Math.round(Math.min(100, Math.max(0, raw)) * 10) / 10;
}

function isExcludedScoreKey(normalized: string): boolean {
  return EXCLUDED_SCORE_KEYS.has(normalized);
}

/** True when the key name itself is an explicit AI-probability field. */
export function isAiProbabilityKey(key: string): boolean {
  const n = normalizeKey(key);
  if (!n || isExcludedScoreKey(n)) return false;
  if (EXPLICIT_PROBABILITY_KEYS.has(n)) return true;

  const hasAiTopic =
    n.startsWith("ai") ||
    n.startsWith("generative") ||
    n.startsWith("synthetic") ||
    n.startsWith("deepfake") ||
    n.startsWith("genai") ||
    n.includes("aigenerat") ||
    n.includes("generatedcontent");

  const hasScoreSense =
    n.includes("prob") ||
    n.includes("likelihood") ||
    n.includes("score") ||
    n.includes("confidence") ||
    n.includes("detection");

  // Require both an AI topic and a score-like suffix; reject bare "aiscore".
  if (!hasAiTopic || !hasScoreSense) return false;
  if (n === "aiscore" || n === "aiscores") return false;
  return true;
}

/** True when the key name itself is an explicit AI Yes/No field. */
export function isAiBooleanKey(key: string): boolean {
  const n = normalizeKey(key);
  if (!n || isExcludedScoreKey(n)) return false;
  if (EXPLICIT_BOOLEAN_KEYS.has(n)) return true;
  return n.endsWith("aigenerated") || n === "aigeneratedcontent";
}

function parseBoolean(value: unknown): boolean | null {
  if (typeof value === "boolean") return value;
  if (typeof value === "number" && Number.isFinite(value)) {
    if (value === 1) return true;
    if (value === 0) return false;
    return null;
  }
  if (typeof value !== "string") return null;
  const v = value.trim().toLowerCase();
  if (["true", "yes", "y", "1"].includes(v)) return true;
  if (["false", "no", "n", "0"].includes(v)) return false;
  return null;
}

/**
 * Interpret an engine classification string as AI vs human when the string
 * itself is an explicit AI-generation label (not authenticity/fraud wording).
 */
export function parseAiClassificationLabel(raw: string | null | undefined): boolean | null {
  if (raw == null) return null;
  const v = raw.trim().toLowerCase().replace(/[_-]+/g, " ").replace(/\s+/g, " ");
  if (!v) return null;

  if (
    v === "ai generated" ||
    v === "ai generated content" ||
    v === "ai edited" ||
    v === "generated by ai" ||
    v === "synthetic" ||
    v === "deepfake" ||
    v === "artificial"
  ) {
    return true;
  }

  if (
    v === "real" ||
    v === "human" ||
    v === "human generated" ||
    v === "not ai generated" ||
    v === "not ai" ||
    v === "organic"
  ) {
    return false;
  }

  if (
    /\b(ai\s*generat|ai\s*edit|artificial|synthetic|deepfake)\b/.test(v) &&
    !/\bnot\b/.test(v)
  ) {
    return true;
  }
  if (/\b(did not detect ai|no ai|not ai)\b/.test(v)) {
    return false;
  }
  if (/^\s*real\b/.test(v) || /\bhuman\s*generat/.test(v)) {
    return false;
  }

  return null;
}

interface ExtractedAiFields {
  probability: number | null;
  isAiGenerated: boolean | null;
}

/**
 * Walk nested response bags and collect the first explicit AI probability
 * and/or AI boolean. Does not invent values from unrelated scores.
 */
export function extractAiFieldsFromPools(
  pools: Array<Record<string, unknown> | null | undefined>,
  depthLimit = 5
): ExtractedAiFields {
  let probability: number | null = null;
  let isAiGenerated: boolean | null = null;

  const walk = (node: unknown, depth: number): void => {
    if (depth > depthLimit || node == null) return;
    if (Array.isArray(node)) {
      for (const item of node) walk(item, depth + 1);
      return;
    }
    const rec = asRecord(node);
    if (!Object.keys(rec).length) return;

    for (const [key, value] of Object.entries(rec)) {
      if (probability == null && isAiProbabilityKey(key) && typeof value === "number") {
        const score = toScore100(value);
        if (score != null) probability = score;
      }
      if (isAiGenerated == null && isAiBooleanKey(key)) {
        const flag = parseBoolean(value);
        if (flag != null) isAiGenerated = flag;
      }
    }

    for (const value of Object.values(rec)) {
      if (value && typeof value === "object") {
        walk(value, depth + 1);
      }
    }
  };

  for (const pool of pools) {
    if (!pool) continue;
    walk(pool, 0);
    if (probability != null && isAiGenerated != null) break;
  }

  return { probability, isAiGenerated };
}

function labelFromFields(
  probability: number | null,
  isAiGenerated: boolean | null
): AiDetectionLabel {
  if (probability != null) {
    return probability >= 50 ? "Likely AI Generated" : "Likely Human Generated";
  }
  if (isAiGenerated === true) return "Likely AI Generated";
  if (isAiGenerated === false) return "Likely Human Generated";
  return "Unknown";
}

function explanationFromFields(
  probability: number | null,
  isAiGenerated: boolean | null
): string | null {
  if (probability != null) {
    const pct = Math.round(probability);
    return `The verification engine estimates a ${pct}% probability that this document was created or modified using AI-generated content.`;
  }
  if (isAiGenerated === true) {
    return "The verification engine found evidence that the document was generated using AI.";
  }
  if (isAiGenerated === false) {
    return "The verification engine found no evidence that the document was generated using AI.";
  }
  return null;
}

/** Build the shared frontend AI detection model from explicit fields only. */
export function buildAiDetection(fields: {
  probability?: number | null;
  isAiGenerated?: boolean | null;
}): AiDetection {
  const probability =
    fields.probability != null && Number.isFinite(fields.probability)
      ? toScore100(fields.probability)
      : null;
  const isAiGenerated = fields.isAiGenerated ?? null;
  const supported = probability != null || isAiGenerated != null;

  if (!supported) {
    return UNSUPPORTED_AI_DETECTION;
  }

  return {
    supported: true,
    probability,
    label: labelFromFields(probability, isAiGenerated),
    explanation: explanationFromFields(probability, isAiGenerated),
  };
}

/**
 * Resolve Yes/No for UI when the engine returned a boolean (or an equivalent
 * classification) but no probability. Null when probability is shown instead
 * or when detection is unsupported.
 */
export function aiDetectionYesNo(detection: AiDetection): "Yes" | "No" | null {
  if (!detection.supported || detection.probability != null) return null;
  if (detection.label === "Likely AI Generated") return "Yes";
  if (detection.label === "Likely Human Generated") return "No";
  return null;
}
