/**
 * Builds and downloads a verification investigation report as Markdown.
 */

import type { VerificationResult } from "../types/verification";
import { ACTIVE_ENGINE_DISPLAY_NAME } from "../config/vendors";

function safeFileStem(name: string): string {
  const stem = name.replace(/\.[^.]+$/, "").trim() || "certificate";
  return stem.replace(/[^\w\-]+/g, "_").slice(0, 80);
}

function buildReportMarkdown(
  result: VerificationResult,
  fileName: string
): string {
  const lines: string[] = [
    "# Certificate Verification Report",
    "",
    `Generated: ${new Date().toISOString()}`,
    `Engine: ${ACTIVE_ENGINE_DISPLAY_NAME}`,
    "",
    "## Overview",
    "",
    `| Field | Value |`,
    `| --- | --- |`,
    `| File | ${fileName} |`,
    `| Certificate ID | ${result.certificateId || "—"} |`,
    `| Verdict | ${result.verdict} |`,
    `| Confidence | ${result.confidence}% |`,
    `| Document Type | ${result.documentType} |`,
    `| Holder | ${result.holderName} |`,
    `| Issuing Authority | ${result.issuingAuthority} |`,
    `| Verified At | ${result.verifiedAt || "—"} |`,
    "",
    "## Executive Summary",
    "",
    result.aiSummary || result.report.summary || "No summary available.",
    "",
    "## Risk Assessment",
    "",
    `- Risk level: ${result.report.riskLevel}`,
    `- Risk score: ${result.report.riskScore}/100`,
    `- Recommendation: ${result.report.recommendation}`,
    "",
  ];

  if (result.vendorFindings.length > 0) {
    lines.push("## Engine Analysis", "");
    for (const finding of result.vendorFindings) {
      lines.push(
        `- **${finding.vendor}** — status: ${finding.status}, confidence: ${Math.round(finding.confidenceScore * 1000) / 10}%`
      );
    }
    lines.push("");
  }

  if (result.report.findings.length > 0) {
    lines.push("## Findings", "");
    for (const finding of result.report.findings) {
      lines.push(`### ${finding.title}`, "", finding.detail, "");
    }
  }

  if (result.signals.length > 0) {
    lines.push("## Forensic Signals", "");
    for (const signal of result.signals) {
      lines.push(
        `- **[${signal.status.toUpperCase()}] ${signal.category}** — ${signal.description}`
      );
    }
    lines.push("");
  }

  lines.push("---", "", "_Generated by CertVerify investigation platform._", "");
  return lines.join("\n");
}

/**
 * Trigger a browser download of the verification report.
 */
export function downloadVerificationReport(
  result: VerificationResult,
  fileName = "certificate"
): void {
  const markdown = buildReportMarkdown(result, fileName);
  const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  const stamp = new Date().toISOString().slice(0, 19).replace(/[:T]/g, "-");
  anchor.href = url;
  anchor.download = `verification-report_${safeFileStem(fileName)}_${stamp}.md`;
  anchor.rel = "noopener";
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  // Revoke after the browser has a chance to start the download.
  window.setTimeout(() => URL.revokeObjectURL(url), 1_000);
}
